import { Question } from './types';

export const QUIZ_QUESTIONS: Question[] = [
  {
    questionText: '¿Cuál es el período del "ejercicio económico" en el sistema Séneca?',
    answers: [
      { answerText: 'Del 1 de enero al 31 de diciembre', isCorrect: false },
      { answerText: 'Del 1 de septiembre al 31 de agosto', isCorrect: false },
      { answerText: 'Del 1 de octubre al 30 de septiembre', isCorrect: true },
      { answerText: 'Es el mismo que el año natural', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'En Séneca, el ejercicio económico se establece desde el 1 de Octubre al 30 de Septiembre, lo que no se corresponde con el año natural. (Documentación del curso, Módulo 2, pág. 5)',
  },
  {
    questionText: '¿Quién tiene la potestad de asignar el perfil de "Responsable de la Gestión Económica"?',
    answers: [
      { answerText: 'Cualquier profesor del centro', isCorrect: false },
      { answerText: 'Solo el/la director/a del centro o un cargo equivalente', isCorrect: true },
      { answerText: 'La consejería de educación regional', isCorrect: false },
      { answerText: 'El responsable de informática', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'Solo la persona que ostenta el cargo de director/a del centro (o similar) puede asignar el perfil de "Responsable de la Gestión Económica" a otro empleado o a sí mismo. (Documentación del curso, Módulo 2, pág. 6)',
  },
   {
    questionText: '¿Con qué frecuencia se debe realizar el "Arqueo de caja (Anexo XIII)"?',
    answers: [
      { answerText: 'Semanalmente', isCorrect: false },
      { answerText: 'Mensualmente', isCorrect: true },
      { answerText: 'Trimestralmente', isCorrect: false },
      { answerText: 'Anualmente', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'Según la misma norma mencionada para el anexo XII, el arqueo de caja o anexo XIII se hará mensualmente para controlar los movimientos y el saldo de caja. (Documentación del curso, Módulo 6, pág. 22)',
  },
  {
    questionText: '¿A partir de qué valor unitario es obligatorio incluir un bien en el inventario del centro?',
    answers: [
      { answerText: '150,25 euros', isCorrect: false },
      { answerText: '600 euros', isCorrect: false },
      { answerText: '300,50 euros', isCorrect: true },
      { answerText: '1000 euros', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'La normativa obliga a incluir en el inventario los bienes considerados material inventariable con un valor superior a 300,50 euros. (Documentación del curso, Módulo 4 (I), pág. 11)',
  },
  {
    questionText: 'Si un ingreso tiene un carácter finalista (Justificación Específica), ¿puede el centro usar un remanente para otro objetivo?',
    answers: [
      { answerText: 'Sí, siempre que lo apruebe el Consejo Escolar', isCorrect: false },
      { answerText: 'No, los fondos deben imputarse a esa finalidad y no a otra', isCorrect: true },
      { answerText: 'Sí, si el importe es menor de 600 euros', isCorrect: false },
      { answerText: 'Solo si se devuelve a la Consejería primero', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'Los fondos destinados a programas específicos deben imputarse a esa finalidad y no a otra. El excedente quedaría para la misma actuación en periodos sucesivos. (Documentación del curso, Módulo 2 (II), pág. 17)',
  },
  {
    questionText: '¿Qué perfil tiene acceso automático al módulo de Gestión Económica sin necesidad de permisos adicionales?',
    answers: [
      { answerText: 'El "Responsable de la Gestión Económica"', isCorrect: false },
      { answerText: 'El/la Director/a del centro', isCorrect: true },
      { answerText: 'Cualquier usuario con perfil "Dirección"', isCorrect: false },
      { answerText: 'El secretario del centro', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'La persona que ostenta el cargo de director/a o equivalente tiene acceso al módulo de Gestión Económica automáticamente, sin necesidad de ninguna actuación ni concesión de permiso adicional. (Documentación del curso, Módulo 2, pág. 5)',
  },
   {
    questionText: '¿Qué es el PUEF?',
    answers: [
      { answerText: 'El Protocolo Unificado de Escrutinio Final', isCorrect: false },
      { answerText: 'El Punto General de Entrada de Facturas Electrónicas de la Comunidad Autónoma de Andalucía', isCorrect: true },
      { answerText: 'El Plan Unificado de Evaluación de Fondos', isCorrect: false },
      { answerText: 'El Portal Único de Empleados Financieros', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'Las facturas electrónicas se presentan en el Punto General de Entrada de Facturas Electrónicas (PUEF) de la Comunidad Autónoma de Andalucía para su posterior remisión al centro educativo. (Módulo 4 (I), pág. 63)',
  },
  {
    questionText: '¿Cuál es el saldo máximo de dinero permitido en caja?',
    answers: [
      { answerText: '300 euros', isCorrect: false },
      { answerText: '1000 euros', isCorrect: false },
      { answerText: '600 euros', isCorrect: true },
      { answerText: 'No hay límite', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'Se sabe que en la caja no puede haber más de 600 euros. Si se supera este saldo, el excedente debe ingresarse en el banco. (Módulo 4 (I), pág. 17)',
  },
  {
    questionText: '¿En qué menú se gestionan los "claveros" o personas autorizadas para operar con la cuenta bancaria?',
    answers: [
      { answerText: 'Gestión Económica / Gestión de Claveros', isCorrect: true },
      { answerText: 'Personal / Autorizaciones bancarias', isCorrect: false },
      { answerText: 'Configuración / Cuentas bancarias', isCorrect: false },
      { answerText: 'Documentos / Firmas', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'La gestión de claveros se realiza en el apartado Gestión Económica / Gestión de Claveros, y solo puede hacerlo la persona con perfil Dirección o similar. (Módulo 2, pág. 12)',
  },
  {
    questionText: '¿Para qué se utiliza el asiento "Movimientos entre caja y banco"?',
    answers: [
      { answerText: 'Para pagar facturas', isCorrect: false },
      { answerText: 'Para registrar los intereses generados', isCorrect: false },
      { answerText: 'Para traspasar dinero entre la caja y la cuenta bancaria del centro', isCorrect: true },
      { answerText: 'Para registrar ingresos de la Consejería', isCorrect: false },
    ],
    difficulty: 'easy',
    explanation: 'Este tipo de asiento se usa para indicar operaciones de traspaso de dinero desde el banco a la caja o viceversa, por ejemplo, para no superar el excedente de 600€ en caja. (Módulo 4 (I), pág. 17)',
  },
  {
    questionText: '¿Qué es un "Centro de Gasto"?',
    answers: [
      { answerText: 'La oficina bancaria principal del centro', isCorrect: false },
      { answerText: 'Una herramienta discrecional para controlar gastos por departamento, curso o finalidad', isCorrect: true },
      { answerText: 'Un proveedor principal del centro educativo', isCorrect: false },
      { answerText: 'Un tipo de subcuenta obligatorio para gastos de funcionamiento', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'El uso de los "Centros de Gasto" es discrecional y sirve para llevar un control más exhaustivo sobre el destino de los recursos económicos, por ejemplo, por departamento o por grupo. (Módulo 2 (II), pág. 15)',
  },
  {
    questionText: '¿Para qué se utiliza principalmente el fichero Q34?',
    answers: [
      { answerText: 'Para registrar la asistencia de los alumnos', isCorrect: false },
      { answerText: 'Para generar ficheros de transferencias bancarias para pagar a proveedores', isCorrect: true },
      { answerText: 'Para gestionar los cobros a las familias', isCorrect: false },
      { answerText: 'Para declarar impuestos a la AEAT', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Las Órdenes de Pago Q34, o "Cuadernos de Transferencias", son una remesa de facturas que se envían al banco para que éste proceda al pago de las mismas. (Documentación del curso, Módulo 4 (II), pág. 7)',
  },
  {
    questionText: 'Según el "Decreto de garantía", ¿cuál es el plazo máximo para dar "conformidad" a una factura tras su fecha de entrada?',
    answers: [
      { answerText: '10 días', isCorrect: false },
      { answerText: '20 días', isCorrect: false },
      { answerText: '30 días', isCorrect: true },
      { answerText: '60 días', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'A partir de la fecha de entrada de la factura, hay que hacer la operación de "conformidad" antes de 30 días máximo. A partir de ese día, se inicia el plazo de pago de 20 días. (Documentación del curso, Módulo 4 (I), pág. 7)',
  },
  {
    questionText: '¿Qué es un "Asiento de apertura"?',
    answers: [
      { answerText: 'El resumen final del ejercicio económico', isCorrect: false },
      { answerText: 'El asiento que indica los saldos iniciales para un nuevo ejercicio económico', isCorrect: true },
      { answerText: 'Un asiento especial para la gestión de contratos', isCorrect: false },
      { answerText: 'La primera factura que se introduce en el sistema', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'El asiento de apertura indica los saldos iniciales (remanentes del ejercicio anterior y saldos de caja y banco) con los que parte el centro para el nuevo ejercicio económico. Es un paso obligatorio. (Documentación del curso, Módulo 2, pág. 19)',
  },
  {
    questionText: '¿Qué es un "Asiento predefinido" o plantilla?',
    answers: [
      { answerText: 'Una factura que se paga por adelantado', isCorrect: false },
      { answerText: 'Un borrador de asiento que no se puede modificar', isCorrect: false },
      { answerText: 'Un "pre-asiento" para facilitar la grabación de facturas repetitivas', isCorrect: true },
      { answerText: 'Un tipo de asiento exclusivo para ingresos', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Las plantillas o asientos predefinidos son instrumentos que ayudan a introducir facturas muy repetitivas, conteniendo datos que se repiten para no tener que introducirlos cada vez. (Documentación del curso, Módulo 2 (II), pág. 25)',
  },
  {
    questionText: '¿A partir de qué importe es obligatorio dar de alta un contrato en Séneca, salvo excepciones?',
    answers: [
      { answerText: '1.000 euros', isCorrect: false },
      { answerText: '5.000 euros', isCorrect: false },
      { answerText: '3.000 euros', isCorrect: true },
      { answerText: '600 euros', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Es obligatorio dar de alta en el registro de contratos todos aquellos que tengan un importe superior a 3.000 euros, con excepciones como el pago de cheque libros o el suministro de agua. (Documentación del curso, Módulo 5, pág. 8)',
  },
  {
    questionText: '¿Para qué se utilizan los ficheros de "Domiciliaciones de adeudos Q19"?',
    answers: [
      { answerText: 'Para pagar facturas a proveedores extranjeros', isCorrect: false },
      { answerText: 'Para cobrar recibos de servicios a las familias (Comedor, Aula Matinal, etc.)', isCorrect: true },
      { answerText: 'Para comunicar los contratos a la Consejería', isCorrect: false },
      { answerText: 'Para solicitar anticipos de caja', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Los adeudos (Q19) son una remesa de recibos que enviamos al banco para que éste cargue los importes en las cuentas de las familias y los ingrese en nuestra cuenta. (Documentación del curso, Módulo 4 (II), pág. 24)',
  },
  {
    questionText: 'Cuando un profesor recibe un anticipo para un viaje, ¿cómo se registra el pago de las facturas que trae a la vuelta?',
    answers: [
      { answerText: 'Se pagan como una factura normal desde el banco', isCorrect: false },
      { answerText: 'Se indica que han sido pagadas con cargo al anticipo', isCorrect: true },
      { answerText: 'El profesor debe devolver el dinero y se le hace una transferencia', isCorrect: false },
      { answerText: 'No se pueden registrar, se gestionan fuera de Séneca', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Cuando se recibe la factura, esta se introduce en Séneca y en los datos de pago se indica que se ha pagado mediante el anticipo, regularizando así el saldo. (Documentación del curso, Módulo 4 (I), pág. 14)',
  },
  {
    questionText: 'Para que el Anexo XI se considere aprobado, ¿qué condición deben cumplir los votos del Consejo Escolar?',
    answers: [
      { answerText: 'Unanimidad de los asistentes', isCorrect: false },
      { answerText: 'Mayoría simple de los asistentes', isCorrect: false },
      { answerText: 'Al menos la mitad de los votos a favor de los miembros activos', isCorrect: true },
      { answerText: 'Dos tercios de los miembros activos', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Se debe aprobar el Anexo XI por al menos la mitad de los miembros activos del Consejo Escolar en el momento de la celebración de la sesión, no de los asistentes. (Documentación del curso, Módulo 6, pág. 3)',
  },
  {
    questionText: '¿Qué dos situaciones impiden que el botón "Aceptar" de "Gestión de Claveros" esté habilitado?',
    answers: [
      { answerText: 'No tener claveros definidos y que el director no tenga firma digital', isCorrect: false },
      { answerText: 'No haber indicado el email de la entidad bancaria o tener un cambio de clavero pendiente de firma', isCorrect: true },
      { answerText: 'Tener saldo negativo en la cuenta y que sea fin de semana', isCorrect: false },
      { answerText: 'No haber cerrado el ejercicio anterior y no tener presupuesto aprobado', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'El icono "Aceptar" está deshabilitado si el centro no tiene indicado el correo electrónico de la entidad bancaria o si ya se ha generado un documento de cambio de clavero que está pendiente de firma electrónica. (Módulo 2, pág. 14)',
  },
  {
    questionText: '¿A qué nivel de subcuenta (como mínimo) se debe asignar una factura o ingreso?',
    answers: [
      { answerText: 'Nivel 1º ó 2º', isCorrect: false },
      { answerText: 'Nivel 3º', isCorrect: false },
      { answerText: 'Nivel 4º ó 5º', isCorrect: true },
      { answerText: 'A cualquier nivel', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'A la hora de asignar una factura o ingreso a una subcuenta, sólo se puede elegir de entre las de nivel 4º ó 5º. Los niveles superiores son agrupadores. (Módulo 2 (II), pág. 14)',
  },
  {
    questionText: 'Si una factura tiene un importe superior a 5.000€ y el proveedor es una persona física (NIF), ¿qué acción adicional se requiere?',
    answers: [
      { answerText: 'Debe ser firmada por el director y el secretario', isCorrect: false },
      { answerText: 'El proveedor debe presentarla en formato electrónico obligatoriamente', isCorrect: false },
      { answerText: 'El centro debe registrarla en el Registro Contable de la Junta de Andalucía', isCorrect: true },
      { answerText: 'Se debe solicitar autorización previa a la Consejería', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Para facturas en papel de personas físicas con importe superior a 5.000€, el centro debe realizar comprobaciones y registrarla en el Registro Contable de facturas de la Administración de la Junta de Andalucía. (Módulo 4 (I), pág. 10)',
  },
  {
    questionText: '¿Qué significa que un asiento de ingreso está "No materializado"?',
    answers: [
      { answerText: 'Que el ingreso se ha anulado', isCorrect: false },
      { answerText: 'Que el sistema ha validado el ingreso, pero la transferencia aún no ha sido ordenada', isCorrect: true },
      { answerText: 'Que es un ingreso en efectivo y no bancario', isCorrect: false },
      { answerText: 'Que el asiento tiene un error y debe ser corregido', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Un asiento "No materializado" significa que, aunque el ingreso ya aparece en Séneca (validado por el sistema GIRO), la transferencia aún no se ha ordenado, por lo que el importe no aparece en la cuenta corriente. (Módulo 3, pág. 7)',
  },
  {
    questionText: '¿Qué es el "Reintegro de anticipo"?',
    answers: [
      { answerText: 'La solicitud de un nuevo anticipo', isCorrect: false },
      { answerText: 'La devolución de un anticipo completo no utilizado', isCorrect: false },
      { answerText: 'El ingreso de la cantidad sobrante de un anticipo después de justificar los gastos', isCorrect: true },
      { answerText: 'La justificación de las facturas pagadas con el anticipo', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Es normal que al justificar un anticipo, el importe de las facturas sea inferior. La cantidad sobrante se ingresa en banco o caja, y esta operación se contabiliza con un asiento de tipo "Reintegro de anticipo". (Módulo 4 (I), pág. 15)',
  },
  {
    questionText: '¿Cuál es la diferencia principal entre un asiento de "Traspaso" y uno de "Pago" entre centros?',
    answers: [
      { answerText: 'No hay ninguna diferencia, son sinónimos', isCorrect: false },
      { answerText: 'El traspaso es un envío de dinero sin contraprestación y el pago corresponde a una compra o servicio', isCorrect: true },
      { answerText: 'El traspaso es para centros de la misma localidad y el pago para distintas localidades', isCorrect: false },
      { answerText: 'El traspaso no requiere firma y el pago sí', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'Un traspaso es cuando se envía parte de un ingreso recibido (ej. de la Consejería) a otro centro sin ser un pago por un servicio. Un pago entre centros es por la adquisición de un bien o servicio. (Módulo 4 (I), pág. 43)',
  },
  {
    questionText: '¿Cuándo se presenta el modelo 190?',
    answers: [
      { answerText: 'Mensualmente, para liquidar el IVA', isCorrect: false },
      { answerText: 'Trimestralmente, para liquidar el IRPF', isCorrect: false },
      { answerText: 'Anualmente, antes del 20 de enero, para informar de las retenciones de IRPF del año anterior', isCorrect: true },
      { answerText: 'Al final de cada ejercicio económico de Séneca', isCorrect: false },
    ],
    difficulty: 'medium',
    explanation: 'El modelo 190 se presenta anualmente, antes del 20 de enero de cada año, para informar a la AEAT de las retenciones de IRPF practicadas durante el año natural anterior. (Módulo 4 (I), pág. 38)',
  },
  {
    questionText: '¿Qué sucede al intentar registrar una factura en papel de un proveedor obligado a facturar electrónicamente?',
    answers: [
      { answerText: 'El sistema lo permite pero muestra una advertencia', isCorrect: false },
      { answerText: 'Se permite si el importe es menor de 5000 euros', isCorrect: false },
      { answerText: 'Séneca avisa y no permite guardarla (salvo si es inferior a 600 euros)', isCorrect: true },
      { answerText: 'Se debe llamar a soporte para obtener un código de autorización', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Cuando un proveedor está obligado a facturar electrónicamente, no se puede registrar una factura en papel si supera los 600 euros. Para importes inferiores, el sistema lo advierte pero permite continuar. (Documentación del curso, Módulo 4 (I), pág. 6)',
  },
  {
    questionText: '¿Cuál es el propósito de los "Centros de Gasto"?',
    answers: [
      { answerText: 'Es una forma obligatoria de clasificar todos los gastos', isCorrect: false },
      { answerText: 'Es una herramienta discrecional para controlar gastos de departamentos o fines específicos', isCorrect: true },
      { answerText: 'Se usa solo para gestionar ingresos de la consejería', isCorrect: false },
      { answerText: 'Es una lista de todos los proveedores del centro', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'El sistema de control del gasto por "Centros de Gasto" no es obligatorio. Es una herramienta útil y discrecional para llevar un control más exhaustivo del destino de los recursos económicos. (Documentación del curso, Módulo 2 (II), pág. 15)',
  },
  {
    questionText: '¿Qué sucede cuando un centro accede por primera vez a un nuevo ejercicio económico en Séneca?',
    answers: [
      { answerText: 'Se copian todas las subcuentas del año anterior', isCorrect: false },
      { answerText: 'El sistema habilita un mapa de cuentas "genérico" solo con las subcuentas obligatorias', isCorrect: true },
      { answerText: 'Se deben crear manualmente todas las subcuentas', isCorrect: false },
      { answerText: 'Hay que importar un fichero de la Consejería', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Al acceder por primera vez a un ejercicio económico nuevo, el sistema automáticamente habilita un mapa de estructura de cuentas “genérico” que contiene únicamente las subcuentas obligatorias. (Documentación del curso, Módulo 2, pág. 25)',
  },
  {
    questionText: '¿Qué es el "Código DIR3" en el contexto de la facturación electrónica?',
    answers: [
      { answerText: 'El NIF del director del centro', isCorrect: false },
      { answerText: 'Una tripleta de códigos que identifica de forma unívoca al centro educativo', isCorrect: true },
      { answerText: 'El código de la cuenta bancaria del centro', isCorrect: false },
      { answerText: 'Un código para acceder al sistema Séneca', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'El código DIR3 (Oficina contable, Unidad tramitadora, Órgano gestor) identifica de forma unívoca al centro educativo a efectos de facturas electrónicas en el Directorio Común de Unidades Orgánicas y Oficinas. (Documentación del curso, Módulo 4 (I), pág. 65)',
  },
  {
    questionText: 'Según la Orden de 10 de mayo de 2006, ¿cuándo deben realizarse las conciliaciones bancarias (Anexo XII)?',
    answers: [
      { answerText: 'Mensualmente, al cierre de cada mes', isCorrect: false },
      { answerText: 'Anualmente, al cierre del ejercicio económico', isCorrect: false },
      { answerText: 'Semestralmente, con referencia al último día de septiembre y marzo', isCorrect: true },
      { answerText: 'Trimestralmente, coincidiendo con la liquidación del IVA', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'La orden establece que se debe hacer semestralmente, estando los datos referidos al último día de los meses de septiembre y marzo. (Documentación del curso, Módulo 6, pág. 21)',
  },
  {
    questionText: '¿Cuál es el propósito del Modelo 347 (Declaración anual de operaciones con terceras personas)?',
    answers: [
      { answerText: 'Liquidar las retenciones de IRPF trimestralmente', isCorrect: false },
      { answerText: 'Realizar la declaración anual de pagos a proveedores', isCorrect: true },
      { answerText: 'Solicitar subvenciones a la Consejería', isCorrect: false },
      { answerText: 'Cerrar el Anexo XI del ejercicio', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'El Modelo 347 es una herramienta para realizar la declaración anual de operaciones que se haya efectuado con terceras personas o entidades (proveedores). (Documentación del curso, Módulo 4 (II), pág. 6)',
  },
  {
    questionText: '¿Cuál es la principal diferencia entre una factura rectificativa "íntegra" y una "por diferencias"?',
    answers: [
      { answerText: 'La íntegra anula la original y la sustituye, mientras que la otra solo ajusta el importe.', isCorrect: true },
      { answerText: 'La íntegra solo puede ser de importe positivo, la otra de importe negativo.', isCorrect: false },
      { answerText: 'La íntegra se envía por PUEF y la otra en papel.', isCorrect: false },
      { answerText: 'No hay diferencia, el proveedor elige el tipo.', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'La rectificativa íntegra sustituye por completo a la factura original ("olvidemos la original, que esta es la que vale"), mientras que la rectificativa por diferencias solo notifica un ajuste (positivo o negativo) sobre la original. (Módulo 4 (I), pág. 72)',
  },
  {
    questionText: 'Si un asiento de un ejercicio cerrado necesita ser asociado a una justificación, ¿cómo se puede hacer?',
    answers: [
      { answerText: 'No se puede, los asientos de ejercicios cerrados son inmodificables.', isCorrect: false },
      { answerText: 'Se debe solicitar la reapertura del ejercicio a la Consejería.', isCorrect: false },
      { answerText: 'Desde la "Consulta de asientos", usando la opción "asociar a una justificación específica" del menú emergente.', isCorrect: true },
      { answerText: 'Creando un nuevo asiento rectificativo en el ejercicio actual.', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Aunque un asiento de un ejercicio cerrado no se puede modificar en sus detalles, existe una opción especial en la "Consulta de asientos" para asociarlo a una justificación/periodo, sin alterar los demás datos. (Módulo 4 (I), pág. 58)',
  },
  {
    questionText: '¿Qué ocurre con un cuaderno de transferencias (Q34) en el método "Editran" después de ser firmado por ambos claveros?',
    answers: [
      { answerText: 'Se descarga un fichero que debe llevarse al banco.', isCorrect: false },
      { answerText: 'El sistema lo envía automáticamente a la Consejería de Hacienda para que lo procese y lo envíe al banco.', isCorrect: true },
      { answerText: 'Se debe imprimir y enviar por correo postal.', isCorrect: false },
      { answerText: 'Cambia a estado "Abonado" y las facturas se marcan como pagadas.', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Una vez firmado por ambos claveros, el cuaderno pasa al estado "FIRMADO". Durante la noche, el sistema lo envía a la Consejería de Hacienda, que a su vez lo remite al banco. (Módulo 4 (II), pág. 20)',
  },
  {
    questionText: '¿Puede un centro abrir un nuevo ejercicio económico sin haber cerrado el anterior (Anexo XI)?',
    answers: [
      { answerText: 'No, es obligatorio cerrar un ejercicio para poder abrir el siguiente.', isCorrect: false },
      { answerText: 'Sí, se pueden tener dos ejercicios abiertos a la vez para gestionar facturas de ambos.', isCorrect: true },
      { answerText: 'Solo si se solicita una autorización especial a la Delegación.', isCorrect: false },
      { answerText: 'Sí, pero no se podrán registrar gastos en el nuevo hasta que el anterior se cierre.', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Es posible y común tener dos ejercicios abiertos simultáneamente para gestionar facturas correspondientes a ambos. No es necesario cerrar el ejercicio actual para abrir el siguiente. (Módulo 6, pág. 5)',
  },
   {
    questionText: 'Si un proveedor está embargado y se introduce una factura suya, ¿qué hace el sistema Séneca?',
    answers: [
      { answerText: 'Bloquea el registro de la factura hasta que se levante el embargo', isCorrect: false },
      { answerText: 'Advierte del embargo y fija automáticamente la cuenta corriente del organismo embargante para el pago', isCorrect: true },
      { answerText: 'Envía una alerta al director pero permite el pago al proveedor', isCorrect: false },
      { answerText: 'Reduce el importe de la factura en la cantidad del embargo', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Si un proveedor está embargado, el sistema lo comunica automáticamente y fija la cuenta corriente del órgano embargante, de modo que la transferencia se haga inevitablemente a dicha CC y no a la del proveedor. (Módulo 4 (I), pág. 5)',
  },
  {
    questionText: '¿Qué es el "Sufijo de ordenante" en el contexto de los ficheros bancarios Q19/Q34?',
    answers: [
      { answerText: 'Un código que se añade al final del IBAN del centro', isCorrect: false },
      { answerText: 'Un dato proporcionado por la entidad bancaria que identifica al centro como cliente para remesas', isCorrect: true },
      { answerText: 'Los tres últimos dígitos del código del centro educativo', isCorrect: false },
      { answerText: 'Una contraseña para firmar los ficheros de pago', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'El "Sufijo" es un dato que identifica a un cliente (el centro) y que es proporcionado por la oficina bancaria. Es necesario para poder generar cuadernos de transferencia (Q34) o adeudos (Q19). (Módulo 4 (II), pág. 14)',
  },
  {
    questionText: '¿Cuándo se crea automáticamente una "Justificación Específica" en el sistema?',
    answers: [
      { answerText: 'Al inicio de cada ejercicio económico para todas las posibles justificaciones', isCorrect: false },
      { answerText: 'Cuando el centro recibe una orden de pago de un programa concreto y no la tiene creada previamente', isCorrect: true },
      { answerText: 'Solo se pueden crear manualmente por el usuario', isCorrect: false },
      { answerText: 'Cuando se cierra el Anexo XI específico del periodo anterior', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Cuando el centro escolar recibe una orden de pago para un programa y todavía no tiene creada la justificación, el sistema la crea automáticamente para no duplicarla. (Módulo 2 (II), pág. 18)',
  },
  {
    questionText: 'En el Anexo XI, ¿a qué se refiere la "Memoria Justificativa" relacionada con la composición del Consejo Escolar?',
    answers: [
      { answerText: 'Al resumen de todos los gastos e ingresos del ejercicio.', isCorrect: false },
      { answerText: 'A la explicación de por qué el número de miembros activos del Consejo Escolar es diferente al de su constitución.', isCorrect: true },
      { answerText: 'A la lista de todas las facturas pendientes de pago.', isCorrect: false },
      { answerText: 'Al presupuesto del siguiente ejercicio.', isCorrect: false },
    ],
    difficulty: 'hard',
    explanation: 'Si el nº de miembros nombrados y activos en el momento de la reunión es diferente al total de miembros que deberían componer el órgano, se debe explicar el motivo en el campo Memoria Justificativa. (Módulo 6, pág. 3)',
  },
];